services:
  control-plane:
    container_name: orra-control-plane
    image: orra-control-plane-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8005:8005"
    environment:
      - STORAGE_PATH=/app/storage
    volumes:
      - ${HOME}/.orra/storage:/app/storage
    networks:
      - orra-dev-network

networks:
  orra-dev-network:
    name: orra-dev-network
    driver: bridge

